stages:
    - build
    - test
    - deploy

build_src:
    stage: build
    image: python:3.12
    script:
        - python3 -m venv .venv
        - source .venv/bin/activate
        - pip3 install -r docs/requirements.txt
        - pip3 install .
        - python3 -c "import ngsxditto"
    needs: []

test_src:
    stage: test
    image: python:3.12
    script:
        - python3 -m venv .venv
        - source .venv/bin/activate
        - pip3 install pytest pytest-cov
        - pip3 install -r docs/requirements.txt
        - pip3 install -e . 
        - python -c "import ngsxditto, sys; print(ngsxditto.__file__, sys.executable)"
        - pytest --cov=ngsxditto --cov-report=xml:coverage.xml --cov-report=term-missing --cov-report=html tests/test_*.py
    artifacts:
        paths:
            - coverage.xml  # Coverage Report als Artifact speichern
            - htmlcov/  # HTML Report als Artifact speichern
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
    dependencies:
        - build_src
    needs: [build_src]

build_pages:
    stage: deploy
    image: python:3.12
    needs: [test_src]
    script:
        - apt-get update
        - apt-get install -y make pandoc
        - pip3 install -r docs/requirements.txt
        - pip3 install .
        - cd docs
        - ./generate_docs.sh
        - cd ..
        - mv docs/build/html public
    artifacts:
        paths:
          - public
    pages: true  # specifies that this is a Pages job and publishes the default public directory
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    dependencies: [test_src] 
    needs: [test_src]

build_package:
    stage: deploy
    image: python:3.12
    variables:
        TWINE_USERNAME: gitlab-ci-token
        TWINE_PASSWORD: $CI_JOB_TOKEN
    script:
        - pip install .
        - pip install build twine
        - python -m build
        - echo "Package built succesfully, not uploading anywhere."
        #- python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
    #rules:
    #    - if: $CI_COMMIT_BRANCH == "main"
    dependencies: [build_src]
    needs: [build_src, test_src] # only build PyPi package if package can be built and tests run through
